extends Node


# Error difference we use. Angle calculation errors are pretty abismal in Godot
const EPSILON: float = 1e-4

# Generated by chat-GPT
# Utility script for generating UUIDs
func generate_uuid() -> String:
	var rng: RandomNumberGenerator = RandomNumberGenerator.new()
	rng.randomize()
	var bytes: Array[int] = []
	for i: int in range(16):
		bytes.append(rng.randi_range(0, 255))

	# Set the version to 4 (0100)
	bytes[6] = (bytes[6] & 0x0F) | 0x40
	# Set the variant to RFC 4122 (10xx)
	bytes[8] = (bytes[8] & 0x3F) | 0x80

	var hex_str: String = ""
	for b: int in bytes:
		hex_str += String("%02x" % [b])

	return hex_str.substr(0, 8) + "-" + hex_str.substr(8, 4) + "-" + hex_str.substr(12, 4) + "-" + hex_str.substr(16, 4) + "-" + hex_str.substr(20, 12)


func normalize_angle_0_to_2_pi(angle: float) -> float:
	var normalized: float = fmod(angle, 2 * PI)
	if normalized < 0:
		normalized += 2 * PI
	return normalized

# Check if angle matches a within EPSILON.
func check_angle_matches(angle_a: float, angle_b: float) -> bool:
	if abs(angle_difference(angle_a, angle_b)) <= EPSILON:
		return true
	return false


func check_value_epsilon(value: float) -> bool:
	if abs(value) <= EPSILON:
		return true
	elif abs(value - PI) <= EPSILON:
		return false
	assert(false, "Value %f is neither close to 0 nor PI" % value)
	return false
